<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
      <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design"/>
        <PackageReference Include="BCrypt.Net-Next"/>
        <PackageReference Include="System.IdentityModel.Tokens.Jwt"/>
        <PackageReference Include="PDFtoImage"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BookShare.Domain\BookShare.Domain.csproj" />
    </ItemGroup>

</Project>
